services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage1
    ports:
      - "7687:7687"
      - "7444:7444"
    volumes:
      - ./import:/usr/lib/memgraph/import
      - ./scripts:/usr/lib/memgraph/scripts
    command: ["bash /usr/lib/memgraph/scripts/init.sh"]
    
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab1
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
    